import { useState } from "react";
import { Badge, Form, Table } from "react-bootstrap";
import TestPageShell from "../components/TestPageShell";
import { TIME_SLOT_SETS } from "../data/mockData";

export default function TimeQuestionSetsScreen() {
  const [selectedSetId, setSelectedSetId] = useState(TIME_SLOT_SETS[0].id);
  const [scheduledTime, setScheduledTime] = useState("09:00");

  const activeSet = TIME_SLOT_SETS.find((s) => s.id === selectedSetId) ?? TIME_SLOT_SETS[0];

  const matchedSet = (() => {
    const hour = parseInt(scheduledTime.split(":")[0], 10);
    if (hour < 12) return TIME_SLOT_SETS[0];
    if (hour < 17) return TIME_SLOT_SETS[1];
    return TIME_SLOT_SETS[2];
  })();

  return (
    <TestPageShell>
      <div className="overflow-auto px-4 py-3" style={{ height: "calc(100vh - 150px)" }}>
        <div className="card shadow-sm border-0 mb-3">
          <div className="card-body p-2">
            <div className="row g-2">
              <div className="col-md-6">
                <Form.Group>
                  <Form.Label className="fw-semibold">Scheduled Start Time</Form.Label>
                  <Form.Control
                    type="time"
                    value={scheduledTime}
                    onChange={(e) => {
                      setScheduledTime(e.target.value);
                      const hour = parseInt(e.target.value.split(":")[0], 10);
                      const set =
                        hour < 12
                          ? TIME_SLOT_SETS[0]
                          : hour < 17
                            ? TIME_SLOT_SETS[1]
                            : TIME_SLOT_SETS[2];
                      setSelectedSetId(set.id);
                    }}
                  />
                </Form.Group>
              </div>
              <div className="col-md-6">
                <Form.Group>
                  <Form.Label className="fw-semibold">Auto-matched Set</Form.Label>
                  <Form.Control
                    value={`${matchedSet.name} (${matchedSet.timeSlot})`}
                    disabled
                  />
                </Form.Group>
              </div>
            </div>
          </div>
        </div>

        <div className="row g-2 mb-3">
          {TIME_SLOT_SETS.map((set) => (
            <div key={set.id} className="col-md-4">
              <div
                role="button"
                className={`p-3 bg-white rounded border shadow-sm test-card-clickable h-100${selectedSetId === set.id ? " border-primary" : ""}`}
                onClick={() => setSelectedSetId(set.id)}
              >
                <div className="d-flex justify-content-between mb-1">
                  <span className="fw-semibold">{set.name}</span>
                  {set.autoGenerated && <Badge bg="info">Auto</Badge>}
                </div>
                <div className="text-secondary small">{set.timeSlot}</div>
                <div className="small mt-2">
                  {set.questions.length} questions ·{" "}
                  {set.questions.reduce((s, q) => s + q.marks, 0)} marks
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="card shadow-sm border-0 mb-3">
          <div className="card-header bg-white d-flex justify-content-between">
            <span className="fw-semibold">{activeSet.name} — Questions</span>
            <Badge bg="primary">{activeSet.timeSlot}</Badge>
          </div>
          <div className="card-body p-0">
            <Table responsive className="mb-0 test-sticky-table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>ID</th>
                  <th>Question</th>
                  <th>Topic</th>
                  <th>Level</th>
                  <th>Type</th>
                  <th>Marks</th>
                </tr>
              </thead>
              <tbody>
                {activeSet.questions.map((q, i) => (
                  <tr key={q.id}>
                    <td className="text-secondary">{i + 1}</td>
                    <td className="fw-semibold">{q.id}</td>
                    <td>{q.text}</td>
                    <td className="text-secondary">{q.topic}</td>
                    <td>
                      <Badge bg="secondary">L{q.level}</Badge>
                    </td>
                    <td>
                      <Badge bg="primary">{q.type}</Badge>
                    </td>
                    <td>{q.marks}</td>
                  </tr>
                ))}
              </tbody>
            </Table>
          </div>
        </div>

        <div className="card shadow-sm border-0">
          <div className="card-header bg-white fw-semibold">Slot Mapping Rules</div>
          <div className="card-body p-0">
            <Table responsive className="mb-0">
              <thead>
                <tr>
                  <th>Time Range</th>
                  <th>Question Set</th>
                  <th>Pool Size</th>
                  <th>Strategy</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>06:00 – 11:59</td>
                  <td>Morning Slot Set</td>
                  <td>40 questions</td>
                  <td>Randomized per level rules</td>
                </tr>
                <tr>
                  <td>12:00 – 16:59</td>
                  <td>Afternoon Slot Set</td>
                  <td>40 questions</td>
                  <td>Randomized per level rules</td>
                </tr>
                <tr>
                  <td>17:00 – 23:59</td>
                  <td>Evening Slot Set</td>
                  <td>40 questions</td>
                  <td>Randomized per level rules</td>
                </tr>
              </tbody>
            </Table>
          </div>
        </div>
      </div>
    </TestPageShell>
  );
}
