export type TestType =
  | "Weekly Test"
  | "Revision Test"
  | "Practice Test"
  | "Subject Final Test"
  | "Overall Test"
  | "Employability Test";

export type LevelRule = {
  level: number;
  label: string;
  questionCount: number;
  marksPerQuestion: number;
  passingPercent: number;
  difficulty: "Easy" | "Medium" | "Hard";
};

export type Question = {
  id: string;
  text: string;
  subject: string;
  topic: string;
  subtopic: string;
  level: number;
  marks: number;
  type: "MCQ" | "Coding";
};

export type SubtopicLevelCounts = {
  level: number;
  mcqCount: number;
  codingCount: number;
};

export type SubtopicQuestionRule = {
  topic: string;
  subtopic: string;
  /** Set when selection logic spans multiple subjects */
  subject?: string;
  levelCounts: SubtopicLevelCounts[];
};

export type QuestionSelectionLogic = {
  subject: string;
  /** Practice / overall tests may select multiple subjects */
  subjects?: string[];
  topics: string[];
  subtopics: string[];
  subtopicRules: SubtopicQuestionRule[];
};

export type SlotAssignStatus = "draft" | "assigned" | "live" | "completed";

export type ScheduleSlotState = {
  questionIds: string[];
  confirmed: boolean;
  assignStatus: SlotAssignStatus;
  triggeredAt?: string | null;
  triggeredTime?: string | null;
  assignedTestName?: string | null;
};

export type ScheduleQuestionConfig = {
  logic: QuestionSelectionLogic;
  questionIds: string[];
  logicSaved: boolean;
  confirmed: boolean;
};

export type QuestionSet = {
  id: string;
  name: string;
  timeSlot: string;
  scheduledStart: string;
  questions: Question[];
  autoGenerated: boolean;
};

export type Student = {
  id: string;
  name: string;
  college: string;
  branch: string;
  attendanceStatus: "Present" | "Absent" | "Pending";
  currentQuestionId?: string;
  testStatus: "Assigned" | "In Progress" | "Completed" | "Absent";
};

export type DraftTest = {
  testId: string;
  name: string;
  description: string;
  durationMinutes: number;
  marks: number;
  testType: TestType;
  subject: string;
  track: string;
  levelRules: LevelRule[];
};

export type LiveTestSession = {
  testId: string;
  testName: string;
  batchName: string;
  startedAt: string;
  durationMinutes: number;
  elapsedMinutes: number;
  attendanceWindowMinutes: number;
  attendanceWindowRemaining: number;
  students: Student[];
};
