import type { DraftTest, LevelRule, LiveTestSession, Question, QuestionSet, Student } from "../types";

export const SUBJECTS = ["Data Structures", "DBMS", "Operating Systems", "Networks"];
export const TRACKS = ["Full Stack Development", "Data Science", "Cloud Computing"];
export const COURSES = ["FS-2024-Batch-A", "FS-2024-Batch-B"];
export const BATCHES = ["Batch-01", "Batch-02", "Batch-03"];

export const DEFAULT_LEVEL_RULES: LevelRule[] = [
  { level: 1, label: "Foundation", questionCount: 5, marksPerQuestion: 2, passingPercent: 40, difficulty: "Easy" },
  { level: 2, label: "Intermediate", questionCount: 8, marksPerQuestion: 3, passingPercent: 50, difficulty: "Medium" },
  { level: 3, label: "Advanced", questionCount: 7, marksPerQuestion: 5, passingPercent: 60, difficulty: "Hard" },
];

export const MOCK_QUESTIONS: Question[] = [
  { id: "Q-101", text: "What is the time complexity of binary search?", subject: "Data Structures", topic: "Algorithms", subtopic: "Complexity", level: 1, marks: 2, type: "MCQ" },
  { id: "Q-102", text: "Explain stack vs queue with examples", subject: "Data Structures", topic: "Data Structures", subtopic: "Stacks", level: 1, marks: 2, type: "MCQ" },
  { id: "Q-201", text: "Implement LRU cache eviction policy", subject: "Data Structures", topic: "Data Structures", subtopic: "Caching", level: 2, marks: 3, type: "Coding" },
  { id: "Q-202", text: "Normalize a database to 3NF", subject: "DBMS", topic: "DBMS", subtopic: "Normalization", level: 2, marks: 3, type: "MCQ" },
  { id: "Q-203", text: "Compare B-Tree and B+ Tree indexing", subject: "DBMS", topic: "DBMS", subtopic: "Indexing", level: 2, marks: 3, type: "MCQ" },
  { id: "Q-301", text: "Design a thread-safe producer-consumer queue", subject: "Operating Systems", topic: "OS", subtopic: "Concurrency", level: 3, marks: 5, type: "Coding" },
  { id: "Q-302", text: "Solve dining philosophers without deadlock", subject: "Operating Systems", topic: "OS", subtopic: "Deadlocks", level: 3, marks: 5, type: "Coding" },
  { id: "Q-303", text: "TCP vs UDP — when to use each?", subject: "Networks", topic: "Networks", subtopic: "Transport", level: 3, marks: 5, type: "MCQ" },
];

export const TIME_SLOT_SETS: QuestionSet[] = [
  {
    id: "SET-MORNING",
    name: "Morning Slot Set",
    timeSlot: "09:00 – 11:00",
    scheduledStart: "09:00",
    autoGenerated: true,
    questions: [MOCK_QUESTIONS[0], MOCK_QUESTIONS[2], MOCK_QUESTIONS[4], MOCK_QUESTIONS[5]],
  },
  {
    id: "SET-AFTERNOON",
    name: "Afternoon Slot Set",
    timeSlot: "14:00 – 16:00",
    scheduledStart: "14:00",
    autoGenerated: true,
    questions: [MOCK_QUESTIONS[1], MOCK_QUESTIONS[3], MOCK_QUESTIONS[6], MOCK_QUESTIONS[7]],
  },
  {
    id: "SET-EVENING",
    name: "Evening Slot Set",
    timeSlot: "17:00 – 19:00",
    scheduledStart: "17:00",
    autoGenerated: true,
    questions: [MOCK_QUESTIONS[0], MOCK_QUESTIONS[3], MOCK_QUESTIONS[5], MOCK_QUESTIONS[7]],
  },
];

export const MOCK_STUDENTS: Student[] = [
  { id: "STU-001", name: "Aarav Sharma", college: "IIT Delhi", branch: "CSE", attendanceStatus: "Present", currentQuestionId: "Q-201", testStatus: "In Progress" },
  { id: "STU-002", name: "Priya Nair", college: "NIT Trichy", branch: "IT", attendanceStatus: "Present", currentQuestionId: "Q-102", testStatus: "In Progress" },
  { id: "STU-003", name: "Rohan Mehta", college: "BITS Pilani", branch: "CSE", attendanceStatus: "Pending", testStatus: "Assigned" },
  { id: "STU-004", name: "Sneha Reddy", college: "IIIT Hyderabad", branch: "CSE", attendanceStatus: "Absent", testStatus: "Absent" },
  { id: "STU-005", name: "Karan Singh", college: "DTU", branch: "ECE", attendanceStatus: "Present", currentQuestionId: "Q-301", testStatus: "In Progress" },
];

export const MOCK_LIVE_SESSION: LiveTestSession = {
  testId: "TST-2401",
  testName: "SQL  - 12M 2026 - FT001",
  batchName: "Batch-01",
  startedAt: "09:00 AM",
  durationMinutes: 120,
  elapsedMinutes: 18,
  attendanceWindowMinutes: 30,
  attendanceWindowRemaining: 12,
  students: MOCK_STUDENTS,
};

export const MOCK_DRAFT_TEST: DraftTest = {
  testId: "TST-NEW",
  name: "",
  description: "",
  durationMinutes: 120,
  marks: 100,
  testType: "Subject Final Test",
  subject: "SQL",
  track: "IT",
  levelRules: DEFAULT_LEVEL_RULES,
};

export function getQuestionSetForTime(time: string): QuestionSet {
  const hour = parseInt(time.split(":")[0], 10);
  if (hour < 12) return TIME_SLOT_SETS[0];
  if (hour < 17) return TIME_SLOT_SETS[1];
  return TIME_SLOT_SETS[2];
}

export function formatDuration(minutes: number): string {
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  if (h && m) return `${h}h ${m}m`;
  if (h) return `${h} hour${h === 1 ? "" : "s"}`;
  return `${m} min`;
}
